### ISSUE TITLE
Guys - beautiful but SPM ??!

### ISSUE THREAD

**Issue by smhk** [dagronf/TinyCSV#2]
Dudes .. surely SPM ??

Pls remove cocoapods which is like so legacy and messy  : O

Thanks!

**Comment by dagronf** [comment]
Hi @smhk, I’m not sure I understand the issue. The package already has SPM support via the Package.swift file. Can you clarify?

cocoapods is needed because a few other cocoapads packages depend on it, so it can’t be removed without causing pain.

- Darren.

**Comment by smhk** [comment]
AHHH!!!!!! 🤪  I'm so sorry I've never used a Package.swift file. I've always just added an SPM via a url.

legacy == makes sense

This library is 1st class.  Much, much better than other csv libraries.  TY so much.

**Comment by dagronf** [comment]
@smhk Thanks for the compliment!  I wrote this library as I couldn't find an existing one that was flexible enough and handled the weirdness with different CSV files.
